//
// BookmarksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class BookmarksAPI {
    /**
     Create a bookmark
     
     - parameter bookmark: (body) JSON with new Bookmark 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createBookmark(bookmark: Bookmark, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        createBookmarkWithRequestBuilder(bookmark: bookmark).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Create a bookmark
     - POST /bookmarks
     - parameter bookmark: (body) JSON with new Bookmark 
     - returns: RequestBuilder<Void> 
     */
    open class func createBookmarkWithRequestBuilder(bookmark: Bookmark) -> RequestBuilder<Void> {
        let path = "/bookmarks"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bookmark)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     List all user's bookmarks
     
     - parameter limit: (query) How many items to return at one time (max 100) (optional, default to 20)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listBookmarks(limit: Int = 20, completion: @escaping ((_ data: [Bookmark]?,_ error: Error?) -> Void)) {
        listBookmarksWithRequestBuilder(limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     List all user's bookmarks
     - GET /bookmarks
     - responseHeaders: [x-next(String)]
     - parameter limit: (query) How many items to return at one time (max 100) (optional, default to 20)
     - returns: RequestBuilder<[Bookmark]> 
     */
    open class func listBookmarksWithRequestBuilder(limit: Int = 20) -> RequestBuilder<[Bookmark]> {
        let path = "/bookmarks"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[Bookmark]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update a specific bookmark
     
     - parameter bookmarkId: (path) The id of the bookmark to update 
     - parameter bookmark: (body) JSON with updated Bookmark 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateBookmarkById(bookmarkId: Int, bookmark: Bookmark, completion: @escaping ((_ data: Bookmark?,_ error: Error?) -> Void)) {
        updateBookmarkByIdWithRequestBuilder(bookmarkId: bookmarkId, bookmark: bookmark).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Update a specific bookmark
     - PATCH /bookmarks/{bookmarkId}
     - parameter bookmarkId: (path) The id of the bookmark to update 
     - parameter bookmark: (body) JSON with updated Bookmark 
     - returns: RequestBuilder<Bookmark> 
     */
    open class func updateBookmarkByIdWithRequestBuilder(bookmarkId: Int, bookmark: Bookmark) -> RequestBuilder<Bookmark> {
        var path = "/bookmarks/{bookmarkId}"
        let bookmarkIdPreEscape = "\(APIHelper.mapValueToPathItem(bookmarkId))"
        let bookmarkIdPostEscape = bookmarkIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{bookmarkId}", with: bookmarkIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bookmark)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Bookmark>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
