//
// TasksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class TasksAPI {
    /**
     Create a task
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createTasks(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        createTasksWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Create a task
     - POST /tasks
     - returns: RequestBuilder<Void> 
     */
    open class func createTasksWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/tasks"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     List all user's tasks
     
     - parameter limit: (query) How many items to return at one time (max 100) (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listTasks(limit: Int? = nil, completion: @escaping ((_ data: [Task]?,_ error: Error?) -> Void)) {
        listTasksWithRequestBuilder(limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     List all user's tasks
     - GET /tasks
     - responseHeaders: [x-next(String)]
     - parameter limit: (query) How many items to return at one time (max 100) (optional)
     - returns: RequestBuilder<[Task]> 
     */
    open class func listTasksWithRequestBuilder(limit: Int? = nil) -> RequestBuilder<[Task]> {
        let path = "/tasks"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[Task]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Info for a specific task
     
     - parameter taskId: (path) The id of the task to retrieve 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func showTaskById(taskId: String, completion: @escaping ((_ data: Task?,_ error: Error?) -> Void)) {
        showTaskByIdWithRequestBuilder(taskId: taskId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Info for a specific task
     - GET /tasks/{taskId}
     - parameter taskId: (path) The id of the task to retrieve 
     - returns: RequestBuilder<Task> 
     */
    open class func showTaskByIdWithRequestBuilder(taskId: String) -> RequestBuilder<Task> {
        var path = "/tasks/{taskId}"
        let taskIdPreEscape = "\(APIHelper.mapValueToPathItem(taskId))"
        let taskIdPostEscape = taskIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{taskId}", with: taskIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Task>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
