openapi: "3.0.0"
info:
  version: 1.0.0
  title: Smartmate API
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /bookmarks:
    get:
      summary: List all user's bookmarks
      operationId: listBookmarks
      tags:
        - bookmarks
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of bookmarks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Bookmarks"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a bookmark
      operationId: createBookmarks
      tags:
        - bookmarks
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /bookmarks/{bookmarkId}:
    get:
      summary: Info for a specific bookmark
      operationId: showBookmarkById
      tags:
        - bookmarks
      parameters:
        - name: bookmarkId
          in: path
          required: true
          description: The id of the bookmark to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bookmark"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks:
    get:
      summary: List all user's tasks
      operationId: listTasks
      tags:
        - tasks
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of tasks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Tasks"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a task
      operationId: createTasks
      tags:
        - tasks
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks/{taskId}:
    get:
      summary: Info for a specific task
      operationId: showTaskById
      tags:
        - tasks
      parameters:
        - name: taskId
          in: path
          required: true
          description: The id of the task to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Bookmark:
      type: object
      required:
        - id
        - name
        - imageUrl
        - isFavorite
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        imageUrl:
          type: string
        isFavorite:
          type: bool
        tag:
          type: string
    Bookmarks:
      type: array
      items:
        $ref: "#/components/schemas/Bookmark"
    Task:
      type: object
      required:
        - id
        - name
        - isResolved
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        isResolved:
          type: bool
        tag:
          type: string
    Tasks:
      type: array
      items:
        $ref: "#/components/schemas/Task"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string